### ISSUE TITLE
Problem with domain validation - DNS-01, opnsense with bind

### ISSUE THREAD

**Issue by wacki4** [acmesh-official/acme.sh#3735]
Hi!
I'am trying to validate with DNS-01 my subdomain using opnsense acme plugin, and bind.

My DNS works without a problem - it is avaiable from outside, and returns correct IP addresses for entrances which i made.

But i cannot generate certificate cause of error: "invalid domain".

I found out that it is returned by  acme.sh/dnsapi/dns_opnsense.sh .

Running /api/bind/domain/get i got in return:

`{
  "domain": {
    "domains": {
      "domain": {
        "19b51657-5206-4a1f-a0a6-98b7eab8eb51": {
          "enabled": "1",
          "type": {
            "master": {
              "value": "master",
              "selected": 1
            },
            "slave": {
              "value": "slave",
              "selected": 0
            }
          },
          "masterip": {
            "": {
              "value": "",
              "selected": 1
            }
          },
          "allownotifyslave": {
            "": {
              "value": "",
              "selected": 1
            }
          },
          "domainname": "test.pl",
          "allowtransfer": {
            "": {
              "value": "none",
              "selected": 0
            },
            "7ff76356-1da2-45bd-a733-52fe959f2518": {
              "value": "all",
              "selected": 1
            }
          },
          "allowquery": {
            "": {
              "value": "none",
              "selected": 0
            },
            "7ff76356-1da2-45bd-a733-52fe959f2518": {
              "value": "all",
              "selected": 1
            }
          },
          "serial": "2110031633",
          "ttl": "86400",
          "refresh": "21600",
          "retry": "3600",
          "expire": "3542400",
          "negative": "3600",
          "mailadmin": "admin.test.pl",
          "dnsserver": "ns.test.pl"
        }
      }
    }
  }
}`

And this is my log where problem occurs:

<html><body>

2021-10-03T16:44:56 | acme.sh[91474] | ] Please check log file for more details: /var/log/acme.sh.log
-- | -- | --
2021-10-03T16:44:56 | acme.sh[7671] | ] _on_issue_err
2021-10-03T16:44:56 | acme.sh[44902] | ] Error add txt for domain:_acme-challenge.aaa.test.pl
2021-10-03T16:44:56 | acme.sh[90579] | ] invalid domain
2021-10-03T16:44:56 | acme.sh[49488] | ] h='pl'
2021-10-03T16:44:56 | acme.sh[79755] | ] h='test.pl'
2021-10-03T16:44:56 | acme.sh[5610] | ] h='aaa.test.pl'
2021-10-03T16:44:55 | acme.sh[90452] | ] _hcode='0'
2021-10-03T16:44:55 | acme.sh[45503] | ] ret='0'
2021-10-03T16:44:55 | acme.sh[48565] | ] _CURL='curl --silent --dump-header /var/etc/acme-client/home/http.header  -L  --trace-ascii /tmp/tmp.xdI3cqrJ  --insecure  '
2021-10-03T16:44:55 | acme.sh[74843] | ] displayError='1'
2021-10-03T16:44:55 | acme.sh[4499] | ] timeout=
2021-10-03T16:44:55 | acme.sh[33181] | ]   url='https://[CUT OFF FOR SECURITY]/api/bind/domain/get'
2021-10-03T16:44:55 | acme.sh[36307] | ] GET
2021-10-03T16:44:55 | acme.sh[56945] | ] Retrying GET
2021-10-03T16:44:55 | acme.sh[30350] | ] Detect root zone

</body>
</html>

Plugin in opnsense is running on version 3.2

**Comment by superwinni2** [comment]
Is there anything new to this?
Or anyting (simple) what I can test?

**Comment by blablup** [comment]
Do a test run with the MR #3764 . I only have subdomains and need domain-alias mode on my opnsense boxes. I just registered a new domain for testing, but am not sure If I can do the test today.

**Comment by superwinni2** [comment]
Sorry but that's too much for me...
I don't know how...

**Comment by superwinni2** [comment]
Something new to this problem?

**Comment by blablup** [comment]
because the mr is merged it should be fixed. I worked on some other fixes to also fix the CI check, but ran into problems with solaris check. I hadn't time to look into that. But this can be closed in my opinion.

**Comment by superwinni2** [comment]
I updated OPNssense to 21.1.1 today... 
It still doesn't work...

My log shows the following:
`<14>1 2022-02-16T15:29:23+01:00 OPNsense1.funny.intern acme.sh 12524 - [meta sequenceId="1"]  [Wed Feb 16 15:29:23 CET 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
<14>1 2022-02-16T15:29:23+01:00 OPNsense1.funny.intern acme.sh 33255 - [meta sequenceId="2"]  [Wed Feb 16 15:29:23 CET 2022] Multi domain='DNS:domain.link,DNS:*.domain.link'
<14>1 2022-02-16T15:29:23+01:00 OPNsense1.funny.intern acme.sh 39663 - [meta sequenceId="3"]  [Wed Feb 16 15:29:23 CET 2022] Getting domain auth token for each domain
<14>1 2022-02-16T15:29:27+01:00 OPNsense1.funny.intern acme.sh 66984 - [meta sequenceId="4"]  [Wed Feb 16 15:29:27 CET 2022] Getting webroot for domain='domain.link'
<14>1 2022-02-16T15:29:27+01:00 OPNsense1.funny.intern acme.sh 78711 - [meta sequenceId="5"]  [Wed Feb 16 15:29:27 CET 2022] Getting webroot for domain='*.domain.link'
<14>1 2022-02-16T15:29:27+01:00 OPNsense1.funny.intern acme.sh 98156 - [meta sequenceId="6"]  [Wed Feb 16 15:29:27 CET 2022] Adding txt value: obnjbs2EuzFKecNvu84pdUzgqvEoHfBC-L73jKnPzks for domain:  _acme-challenge.home.domain.de
<14>1 2022-02-16T15:29:27+01:00 OPNsense1.funny.intern acme.sh 9634  - [meta sequenceId="7"]  [Wed Feb 16 15:29:27 CET 2022] Adding record _acme-challenge.home.domain.de with challenge: obnjbs2EuzFKecNvu84pdUzgqvEoHfBC-L73jKnPzks
<11>1 2022-02-16T15:29:27+01:00 OPNsense1.funny.intern acme.sh 21862 - [meta sequenceId="8"]  [Wed Feb 16 15:29:27 CET 2022] invalid domain
<11>1 2022-02-16T15:29:27+01:00 OPNsense1.funny.intern acme.sh 23626 - [meta sequenceId="9"]  [Wed Feb 16 15:29:27 CET 2022] Error add txt for domain:_acme-challenge.home.domain.de
<11>1 2022-02-16T15:29:27+01:00 OPNsense1.funny.intern acme.sh 25134 - [meta sequenceId="10"] [Wed Feb 16 15:29:27 CET 2022] Please add '--debug' or '--log' to check more details.
<11>1 2022-02-16T15:29:27+01:00 OPNsense1.funny.intern acme.sh 26884 - [meta sequenceId="11"] [Wed Feb 16 15:29:27 CET 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh


Sorry for dumb question..
How do I know if the MR is inserted?

**Comment by richard-9000** [comment]
Debugging this myself, looks like the opnsense bind api has changed again.  Seems to be a pretty fragile 270 character shell/grep regex to blame due to the new section in the domains response:

"transferkeyalgo":{"":{"value":"none","selected":true}
"hmac-sha512":{"value":"HMAC-SHA512","selected":0}
"hmac-sha384":{"value":"HMAC-SHA384","selected":0}
"hmac-sha256":{"value":"HMAC-SHA256","selected":0}
"hmac-sha224":{"value":"HMAC-SHA224","selected":0}
"hmac-sha1":{"value":"HMAC-SHA1","selected":0}
"hmac-md5":{"value":"HMAC-MD5","selected":0}

I'll get a hack working for it, but I wonder if there's any guidance on better json parsing in acme?  A standard json parser wouldn't have these problems.

**Comment by richard-9000** [comment]
https://github.com/acmesh-official/acme.sh/pull/3948

Working againt os-bind 1.19

This will break again without a proper fix / json parser.

**Comment by SBado** [comment]
Fix using **jq**:

```
_get_root() {
  domain=$1
  i=2
  p=1
  if _opns_rest "GET" "/domain/get"; then
    _domain_response="$response"
  else
    return 1
  fi

  while true; do
    h=$(printf "%s" "$domain" | cut -d . -f $i-100)
    if [ -z "$h" ]; then
      #not valid
      return 1
    fi
    _debug h "$h"
    id=$(echo $response | jq -r '.domain.domains.domain | to_entries[] | .key')
    d=$(echo $response | jq --arg i "$id" -r '.domain.domains.domain[$i].domainname')

    if [ -n "$id" ] && [ $d == $h ]; then
      _debug id "$id"
      _host=$(printf "%s" "$domain" | cut -d . -f 1-$p)
      _domain="${h}"
      _domainid="${id}"
      return 0
    fi
    p=$i
    i=$(_math $i + 1)
  done
  _debug "$domain not found"

  return 1
}
```

I'm testing it right now, maybe I will submit a PR later.

**Comment by koelle25** [comment]
Thanks @SBado, I had to modify your jq alternative a bit, because it failed when there are multiple domains in the `$domain_response` (`$id` then had multiple IDs in it and that was when your second jq failed).
[This stackoverflow post](https://stackoverflow.com/a/42051804/5528842) helped me with this and now it seems to work like a charm:
```sh
_get_root() {
  domain=$1
  i=2
  p=1
  if _opns_rest "GET" "/domain/get"; then
    _domain_response="$response"
  else
    return 1
  fi

  while true; do
    h=$(printf "%s" "$domain" | cut -d . -f $i-100)
    if [ -z "$h" ]; then
      #not valid
      return 1
    fi
    _debug h "$h"
    id=$(echo $response | jq --arg h "$h" -r '.domain.domains.domain | with_entries(select(.value.domainname|match($h))) | to_entries[] | .key')

    if [ -n "$id" ]; then
      _debug id "$id"
      _host=$(printf "%s" "$domain" | cut -d . -f 1-$p)
      _domain="${h}"
      _domainid="${id}"
      return 0
    fi
    p=$i
    i=$(_math $i + 1)
  done
  _debug "$domain not found"

  return 1
}
```

Important note for OPNsense users: You'll have to install the `jq` package first. Login via SSH then run:
```sh
sudo pkg install jq
```

**Comment by blablup** [comment]
Sry for late response. I already had a better regex, but I had Problems with the test workflow on some Platforms. I now found a regex which works on all Platforms. 
@SBado  I agree that jq would be nice and easy, but that would add a dependence to acme.sh on all Platforms because this plugin is able to run on remote hosts as well. Also If you still want to use jq you should check that the domain is managed on that host (type:master) and is enabled.

**Comment by koelle25** [comment]
As the PR got merged this issue can be closed now I think. @wacki4 can you close this issue/mark it as resolved?

**Comment by wacki4** [comment]
Still Opnsense has old acme client - new change cannot connect to current version on Bind server. I will check everything when there would be avaiable correct client.

**Comment by koelle25** [comment]
The fix has been integrated into the new 3.0.5 release. Currently OPNsense only delivers version 3.0.4_2. You/we have to wait until the new release arrives in their update repos.

**Comment by wacki4** [comment]
Confirmed - all works great on 22.7.11_1.
