### ISSUE TITLE
Syntax error when executing synology-dsm deployhook in Docker container

### ISSUE THREAD

**Issue by sgilder1** [acmesh-official/acme.sh#4470]
Steps to reproduce
------------------
1. Setup docker container as per https://blog.prabir.me/posts/wildcard-certs-auto-renewal-in-synology-nas-with-dns-challenge-via-acme-sh/
2. Issue certificates (successful)
3. Use symology-dsm deployhook with following command: sudo docker-compose exec acme.sh --deploy --insecure -d mydomain.com --deploy-hook synology_dsm --debug
4. Encounter syntax error as per below

Debug log
-----------------
[Fri Jan 20 18:00:16 CET 2023] Lets find script dir.
[Fri Jan 20 18:00:16 CET 2023] _SCRIPT_='/root/.acme.sh/acme.sh'
[Fri Jan 20 18:00:16 CET 2023] _script='/root/.acme.sh/acme.sh'
[Fri Jan 20 18:00:16 CET 2023] _script_home='/root/.acme.sh'
[Fri Jan 20 18:00:16 CET 2023] Using default home:/root/.acme.sh
[Fri Jan 20 18:00:16 CET 2023] Using config home:/acme.sh
[Fri Jan 20 18:00:16 CET 2023] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.5
[Fri Jan 20 18:00:16 CET 2023] Running cmd: deploy
[Fri Jan 20 18:00:16 CET 2023] Using config home:/acme.sh
[Fri Jan 20 18:00:16 CET 2023] default_acme_server='https://acme-v02.api.letsencrypt.org/directory'
[Fri Jan 20 18:00:16 CET 2023] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Fri Jan 20 18:00:16 CET 2023] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Fri Jan 20 18:00:16 CET 2023] _ACME_SERVER_PATH='directory'
[Fri Jan 20 18:00:16 CET 2023] DOMAIN_PATH='/acme.sh/mydomain.com'
[Fri Jan 20 18:00:16 CET 2023] _deployApi='/root/.acme.sh/deploy/synology_dsm.sh'
[Fri Jan 20 18:00:16 CET 2023] _cdomain='mydomain.com'
[Fri Jan 20 18:00:16 CET 2023] trim quotation marks
[Fri Jan 20 18:00:17 CET 2023] trim quotation marks
/root/.acme.sh/acme.sh: eval: line 2369: syntax error: unterminated quoted string
[Fri Jan 20 18:00:17 CET 2023] Deploy error.

**Comment by sgilder1** [comment]
> Please upgrade to the latest code and try again first. Maybe it's already fixed.              ```acme.sh --upgrade```              If it's still not working, please provide the log with `--debug 2`, otherwise, nobody can help you.

Already upgraded and the log provided is with debug level 2 selected.

**Comment by Neilpang** [comment]
fixed, please try again with the latest `dev` branch.

```
acme.sh  --upgrade -b dev
```

**Comment by sgilder1** [comment]
Many thanks for looking at this.  Unfortunately, I still have the same issue (but the script is updated to dev branch v3.06

[Tue Jan 24 18:14:48 CET 2023] Lets find script dir.
[Tue Jan 24 18:14:48 CET 2023] _SCRIPT_='/root/.acme.sh/acme.sh'
[Tue Jan 24 18:14:48 CET 2023] _script='/root/.acme.sh/acme.sh'
[Tue Jan 24 18:14:48 CET 2023] _script_home='/root/.acme.sh'
[Tue Jan 24 18:14:48 CET 2023] Using default home:/root/.acme.sh
[Tue Jan 24 18:14:48 CET 2023] Using config home:/acme.sh
[Tue Jan 24 18:14:48 CET 2023] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
**v3.0.6**
[Tue Jan 24 18:14:48 CET 2023] Running cmd: deploy
[Tue Jan 24 18:14:48 CET 2023] Using config home:/acme.sh
[Tue Jan 24 18:14:48 CET 2023] default_acme_server='https://acme-v02.api.letsencrypt.org/directory'
[Tue Jan 24 18:14:48 CET 2023] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Jan 24 18:14:48 CET 2023] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Jan 24 18:14:48 CET 2023] _ACME_SERVER_PATH='directory'
[Tue Jan 24 18:14:48 CET 2023] DOMAIN_PATH='/acme.sh/mydomain.com'
[Tue Jan 24 18:14:48 CET 2023] _deployApi='/root/.acme.sh/deploy/synology_dsm.sh'
[Tue Jan 24 18:14:48 CET 2023] _cdomain='mydomain.com'
[Tue Jan 24 18:14:48 CET 2023] trim quotation marks
[Tue Jan 24 18:14:48 CET 2023] trim quotation marks
/root/.acme.sh/acme.sh: eval: line 2389: syntax error: unterminated quoted string
[Tue Jan 24 18:14:48 CET 2023] Deploy error.
ERROR: 1

**Comment by Neilpang** [comment]
show me the file:

```
/acme.sh/mydomain.com/mydomain.com.conf
```

If there are passwords or api key in the file,  you can just  replace some of the chars with '*'.

Thanks

**Comment by sgilder1** [comment]
Here you go:

Le_Domain='mydomain.com'
Le_Alt='*.mydomain.com'
Le_Webroot='dns_cf'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v02.api.letsencrypt.org/directory'
Le_Keylength='2048'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/925***017/160***200817'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/925***017/160***200817'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/04e230c1c83bb7****bce35f47cb43d1ac7d'
Le_CertCreateTime='1674318674'
Le_CertCreateTimeStr='2023-01-21T16:31:14Z'
Le_NextRenewTimeStr='2023-03-21T16:31:14Z'
Le_NextRenewTime='1679416274'
Le_DeployHook='synology_dsm,'

**Comment by Neilpang** [comment]
Can you please show me the `SYNO_*` variables ?  You can mask some of the chars with `*`.

Do they contain any special chars?
